# Generated by Django 5.1 on 2024-08-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_userhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='answer',
            field=models.TextField(null=True),
        ),
    ]
